trigger:
- main

variables:
- group: ClubVerseSecrets

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd client
    npm install
    npm run build
  displayName: 'Build client'

- script: |
    cd server
    npm install
    # node server.js # (Uncomment to run server in CI)
  displayName: 'Install server dependencies'
  env:
    GEMINI_API_KEY: $(GEMINI_API_KEY)

- script: |
    echo "Gemini API Key is: $(GEMINI_API_KEY)"
  displayName: 'Show Gemini API Key (for demo - remove in real use)'

- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- script: |
    cd terraform
    terraform init
    terraform plan
  displayName: 'Terraform plan (demo)'

# --- Docker Build Steps ---
- script: |
    docker build -t clubverse-client:$(Build.BuildId) ./client
    docker build -t clubverse-server:$(Build.BuildId) ./server
  displayName: 'Build Docker images for client and server'

# --- (Optional) Docker Push Steps ---
# To enable pushing, set up Docker Hub or ACR credentials as pipeline secrets and uncomment below:
# - script: |
#     echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
#     docker tag clubverse-client:$(Build.BuildId) yourdockerhub/clubverse-client:$(Build.BuildId)
#     docker tag clubverse-server:$(Build.BuildId) yourdockerhub/clubverse-server:$(Build.BuildId)
#     docker push yourdockerhub/clubverse-client:$(Build.BuildId)
#     docker push yourdockerhub/clubverse-server:$(Build.BuildId)
#   displayName: 'Push Docker images to registry'