version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./server/data:/app/data
