version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - clubverse_net

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./server/data:/app/data
    env_file:
      - ./server/.env
    networks:
      - clubverse_net

networks:
  clubverse_net:
    driver: bridge
