name: DAST Scan (OWASP ZAP)

on:
  workflow_dispatch:  # run manually or trigger on push if you want

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure Docker environment is set up
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Start app with Docker Compose
      - name: Start application containers
        run: |
          docker compose up -d
          echo "Waiting for app containers to start..."
          sleep 25
          docker ps -a

      # Run OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          # Target internal URL (ZAP container will access via Docker network)
          target: "http://client:80"
          docker_name: "clubverse_net"   # custom Docker network name (same as in docker-compose.yml)
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a -r report_html.html -J report_json.json -w report_md.md"

      # Upload scan reports as artifacts
      - name: Upload ZAP Scan Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-reports
          path: |
            report_html.html
            report_json.json
            report_md.md

      # Stop and clean up containers
      - name: Tear down Docker containers
        if: always()
        run: docker compose down
