name: DAST Scan (OWASP ZAP)

on:
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start app with Docker Compose
        run: |
          docker compose up -d
          echo "Waiting for services to be ready..."
          sleep 20

      - name: Verify containers
        run: docker ps -a

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:5173"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a -r report_html.html -J report_json.json -w report_md.md"

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports
          path: |
            report_html.html
            report_json.json
            report_md.md
