name: DAST Scan - OWASP ZAP

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 — Build and run your app using Docker Compose
      - name: Start app with Docker Compose
        run: |
          docker compose up -d
          echo "Waiting for services to be ready..."
          sleep 15  # give containers time to start

      # Step 3 — Run OWASP ZAP Baseline DAST Scan
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'   # change this if your app runs on another port/service
          cmd_options: '--network=host -a'  # active scan mode + access host network
          fail_action: false                # set to true if you want pipeline to fail on high-risk issues

      # Step 4 — Upload the generated ZAP HTML report as a GitHub artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-DAST-Report
          path: report_html.html
