name: DAST Scan (OWASP ZAP)

on:
  workflow_dispatch:
      push:
      branches: [ main ]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Create Docker network explicitly
      - name: Create Docker network
        run: docker network create clubverse_net || echo "Network already exists"

      # Start your app containers
      - name: Start application with Docker Compose
        run: |
          docker compose up -d
          echo "Waiting for app containers to start..."
          sleep 25
          docker ps -a

      # Verify client service readiness
      - name: Verify client service readiness
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5173/ > /dev/null; then
              echo "Client service is ready.";
              exit 0;
            fi;
            echo "Waiting for client service to be ready...";
            sleep 5;
          done;
          echo "Client service is not ready.";
          exit 1;

      # Run OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://client:80"              # internal container URL with a forced error
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-config dirs.work.dir=/zap/wrk/ -a -r report_html.html -J report_json.json -w report_md.md"

      # Inject errors into reports manually
      - name: Inject Errors into Reports
        run: |
          echo '{"error": "Manually injected error for testing purposes."}' > report_json.json
          echo '# Error Report\n\nManually injected error for testing purposes.' > report_md.md
          echo '<html><head><title>Error Report</title></head><body><h1>Error Report</h1><p>Manually injected error for testing purposes.</p></body></html>' > report_html.html

      # Upload reports
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports
          path: |
            report_html.html
            report_json.json
            report_md.md

      # Stop and clean up containers
      - name: Tear down Docker containers
        if: always()
        run: docker compose down