name: "OWASP ZAP Baseline Scan"

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ZAP baseline scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: '${{ secrets.CLIENT_PUBLIC_URL }}'
          fail-on-risk: 'medium'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
